### ISSUE TITLE
Setup matrix CI builds

### ISSUE THREAD

**Issue by lkolbly** [lkolbly/ublox#6]
With the recent additions, this component is starting to have multiple features. The CI pipeline may be able to be setup to support matrix builds.

Along with that, consider the creation of a test suite that talks to actual hardware.

**Comment by Dushistov** [comment]
> The CI pipeline may be able to be setup to support matrix builds.

I should make note that it is rather easy task,
like this in travis.yml
```yaml
env:
  - FEATURES="--features \"default\""
  - FEATURES="--features \"serial\""
```
plus `cargo test $FEATURES` instead of manually select features.

But I chose do not do it, because of VM start is rather expensive, so running 2 (features) * 3 (stable, beta, nightly) can easily double CI runtime, because of travis can postpone 6 VM launch simultaneously, and run 4 VM and then 2 VM or something like this and test time will double,
this of course depend on  travis-ci load and so on things.
